[package]
name = "dailyk√§nguru"
version = "0.1.0"
authors = ["Julian Theis <julian.theis@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8"
log = "0.4"
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot.git" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"